# Generated by Django 4.0.6 on 2022-07-13 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_collection_slug_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
